require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Jollibee_cee' do
  pod 'Smartech-iOS-SDK'
  pod 'SmartPush-iOS-SDK'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'Jollibee_ceeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  
end

#service extension target
target 'SmartechNSE' do
  # Pods for 'SmartechNSE'
  pod 'SmartPush-iOS-SDK'
  
end

#content extension target
target 'SmartechNCE' do
  # Pods for 'SmartechNCE'
  pod 'SmartPush-iOS-SDK'
  
end
